### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by avantgardnerio** [apohrebniak/ignite-rs#8]
My company will likely be using this library in the future, and I have a fork with some improvements:

- support for dynamic types
- sql queries
- limited transaction support

Should we be creating PRs to this repo? If so will they get published to crates.io? If not, should we publish our fork?

Thanks for creating this library, it was a very helpful head start.

**Comment by apohrebniak** [comment]
Your PR's are more than welcome!
> If so will they get published to crates.io?

yes, sure!

**Comment by avantgardnerio** [comment]
Thanks! We'll start sending PRs your way shortly.
